# Generated by Django 5.2.17 on 2026-08-28 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead", "Project Lead"),
                            ("platform_lead", "Platform Engineer Lead"),
                            ("platform_engineer", "Platform Engineer"),
                            ("database_engineer", "Database Engineer"),
                            ("devops", "DevOps / Integration"),
                            ("sdm", "Service Delivery Manager"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="teams.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["role", "name"],
            },
        ),
    ]
