# Generated by Django 5.2.17 on 2026-08-28 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AzureDevOpsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_url",
                    models.URLField(
                        blank=True,
                        help_text="e.g. https://dev.azure.com/your-organization",
                    ),
                ),
                (
                    "personal_access_token",
                    models.CharField(
                        blank=True,
                        help_text="Shared PAT used for all Azure DevOps queries.",
                        max_length=300,
                    ),
                ),
            ],
            options={
                "verbose_name": "Azure DevOps settings",
                "verbose_name_plural": "Azure DevOps settings",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="azure_devops_query_url",
            field=models.URLField(
                blank=True,
                help_text="Shared query link for this person's work items, e.g. https://dev.azure.com/{org}/{project}/_workitems/query/{queryId}/",
            ),
        ),
        migrations.CreateModel(
            name="WorkItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("azure_devops", "Azure DevOps"),
                            ("excel", "Excel / CSV Import"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(max_length=300)),
                ("work_item_type", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "story_points",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("project_label", models.CharField(blank=True, max_length=200)),
                ("area_path", models.CharField(blank=True, max_length=200)),
                ("iteration_path", models.CharField(blank=True, max_length=200)),
                ("created_date", models.DateField(blank=True, null=True)),
                ("closed_date", models.DateField(blank=True, null=True)),
                ("url", models.URLField(blank=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_items",
                        to="teams.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-closed_date", "-created_date"],
            },
        ),
    ]
