# Generated by Django 5.2.17 on 2026-08-28 07:51 (hand-edited to backfill roles before dropping the old field)

from django.db import migrations, models

OLD_ROLE_LABELS = {
    "lead": "Project Lead",
    "platform_lead": "Platform Engineer Lead",
    "platform_engineer": "Platform Engineer",
    "database_engineer": "Database Engineer",
    "devops": "DevOps / Integration",
    "sdm": "Service Delivery Manager",
}

DEFAULT_ROLES = [
    "Project Lead",
    "Platform Engineer Lead",
    "Platform Engineer",
    "Database Engineer",
    "DevOps / Integration",
    "Developer",
    "Service Delivery Manager",
]


def create_default_roles_and_backfill(apps, schema_editor):
    Role = apps.get_model("teams", "Role")
    Employee = apps.get_model("teams", "Employee")

    role_objs = {}
    for order, name in enumerate(DEFAULT_ROLES):
        role, _ = Role.objects.get_or_create(name=name, defaults={"order": order})
        role_objs[name] = role

    for employee in Employee.objects.all():
        label = OLD_ROLE_LABELS.get(employee.role)
        if label:
            employee.roles.add(role_objs[label])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_azuredevopssettings_employee_azure_devops_query_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="employee",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="teams.role"
            ),
        ),
        migrations.RunPython(create_default_roles_and_backfill, noop_reverse),
        migrations.RemoveField(
            model_name="employee",
            name="role",
        ),
    ]
