# Generated by Django 5.2.17 on 2026-08-28 08:21 (hand-edited to backfill from
# existing ticket assignments and project leadership)

from django.db import migrations, models


def backfill_employee_projects(apps, schema_editor):
    Employee = apps.get_model("teams", "Employee")
    Task = apps.get_model("projects", "Task")
    Project = apps.get_model("projects", "Project")

    for employee in Employee.objects.all():
        project_ids = set(
            Task.objects.filter(assignee_id=employee.pk).values_list("project_id", flat=True)
        )
        project_ids.update(
            Project.objects.filter(lead_id=employee.pk).values_list("id", flat=True)
        )
        if project_ids:
            employee.projects.add(*project_ids)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("teams", "0003_role_alter_employee_options_remove_employee_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="team_members", to="projects.project"
            ),
        ),
        migrations.RunPython(backfill_employee_projects, noop_reverse),
    ]
