# Generated by Django 5.2.17 on 2026-08-28 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_employee_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="achievements",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="ai_efficiency",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="AI efficiency %",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="awards",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="designation",
            field=models.CharField(
                blank=True,
                help_text="Job title / grade, e.g. Lead Software Engineer.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="doj",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date of joining"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="emp_id",
            field=models.CharField(blank=True, max_length=20, verbose_name="EMP ID"),
        ),
        migrations.AddField(
            model_name="employee",
            name="escalations",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="gsc_efficiency",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="GSC efficiency %",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="line_manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Skip-level / dotted-line manager, when different from the direct manager.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="line_reports",
                to="teams.employee",
                verbose_name="Line reporting manager",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="rtb_efficiency",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="RTB efficiency %",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="wfh_exceptions",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="WFH exceptions"
            ),
        ),
    ]
