# Generated by Django 5.2.17 on 2026-08-28 08:57

import django.db.models.deletion
from django.db import migrations, models


def backfill_notes(apps, schema_editor):
    Employee = apps.get_model("teams", "Employee")
    EmployeeNote = apps.get_model("teams", "EmployeeNote")
    field_to_category = {
        "wfh_exceptions": "wfh_exception",
        "achievements": "achievement",
        "escalations": "escalation",
    }
    for employee in Employee.objects.all():
        for field_name, category in field_to_category.items():
            value = getattr(employee, field_name, "")
            if value:
                EmployeeNote.objects.create(
                    employee=employee,
                    category=category,
                    description=value,
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_employee_achievements_employee_ai_efficiency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("wfh_exception", "WFH Exception"),
                            ("achievement", "Achievement"),
                            ("escalation", "Escalation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="teams.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.RunPython(backfill_notes, noop_reverse),
        migrations.RemoveField(
            model_name="employee",
            name="achievements",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="escalations",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="wfh_exceptions",
        ),
    ]
