# Generated by Django 5.2.17 on 2026-08-28 09:11

import django.db.models.deletion
import teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0006_remove_employee_achievements_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeenote",
            name="work_item_ref",
            field=models.CharField(
                blank=True,
                help_text="e.g. an Azure DevOps work item number, or a full link to the ticket.",
                max_length=300,
                verbose_name="Linked user story / ticket",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeNoteAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=teams.models.employee_note_attachment_path
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="teams.employeenote",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
