# Generated by Django 5.2.17 on 2026-08-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0007_employeenote_work_item_ref_employeenoteattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="ai_efficiency",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Applies to this person's team, when they're set as someone's manager or line manager.",
                max_digits=5,
                null=True,
                verbose_name="AI efficiency %",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gsc_efficiency",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Applies to this person's team, when they're set as someone's manager or line manager.",
                max_digits=5,
                null=True,
                verbose_name="GSC efficiency %",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="rtb_efficiency",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Applies to this person's team, when they're set as someone's manager or line manager.",
                max_digits=5,
                null=True,
                verbose_name="RTB efficiency %",
            ),
        ),
    ]
