# Generated by Django 5.2.17 on 2026-08-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0008_alter_employee_ai_efficiency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="azuredevopssettings",
            name="team_query_url",
            field=models.URLField(
                blank=True,
                help_text="Shared query link returning user stories for the whole team (across assignees), used by the Analysis tab. e.g. https://dev.azure.com/{org}/{project}/_workitems/query/{queryId}/",
                verbose_name="Team-wide user stories query URL",
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="assigned_to_raw",
            field=models.CharField(
                blank=True,
                help_text="The raw assignee name/email from the source, kept for traceability.",
                max_length=200,
                verbose_name="Assigned to (as imported)",
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="priority",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workitem",
            name="tags",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
