# Generated by Django 5.2.17 on 2026-08-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0009_azuredevopssettings_team_query_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="azuredevopssettings",
            name="auto_sync_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When on, the Analysis tab re-syncs itself in the background at most once per interval below. python manage.py sync_azure_devops does the same sync and can be wired up to an external daily cron for a more reliable schedule.",
                verbose_name="Automatically keep user stories in sync",
            ),
        ),
        migrations.AddField(
            model_name="azuredevopssettings",
            name="auto_sync_interval_hours",
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name="azuredevopssettings",
            name="last_sync_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="azuredevopssettings",
            name="last_sync_item_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="azuredevopssettings",
            name="last_sync_success",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="azuredevopssettings",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
