# Generated by Django 5.2.17 on 2026-08-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0010_azuredevopssettings_auto_sync_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Where this person is based, e.g. India.",
                max_length=100,
            ),
        ),
    ]
