# Generated by Django 5.2.17 on 2026-08-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0011_employee_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
