# Generated by Django 5.2.17 on 2026-08-28 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0012_workitem_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="azuredevopssettings",
            name="support_auto_sync_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Automatically keep support tickets in sync"
            ),
        ),
        migrations.AddField(
            model_name="azuredevopssettings",
            name="support_auto_sync_interval_hours",
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name="azuredevopssettings",
            name="support_last_sync_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="azuredevopssettings",
            name="support_last_sync_item_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="azuredevopssettings",
            name="support_last_sync_success",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="azuredevopssettings",
            name="support_last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="azuredevopssettings",
            name="support_query_url",
            field=models.URLField(
                blank=True,
                help_text="Shared query link returning support tickets for the whole team (across assignees), used by the Support tab. e.g. https://dev.azure.com/{org}/{project}/_workitems/query/{queryId}/",
                verbose_name="Support tickets query URL",
            ),
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("azure_devops", "Azure DevOps"),
                            ("excel", "Excel / CSV Import"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "work_item_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ticket type"
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "story_points",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="Effort",
                    ),
                ),
                ("project_label", models.CharField(blank=True, max_length=200)),
                ("area_path", models.CharField(blank=True, max_length=200)),
                ("iteration_path", models.CharField(blank=True, max_length=200)),
                ("priority", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("tags", models.CharField(blank=True, max_length=300)),
                (
                    "assigned_to_raw",
                    models.CharField(
                        blank=True,
                        help_text="The raw assignee name/email from the source, kept for traceability.",
                        max_length=200,
                        verbose_name="Assigned to (as imported)",
                    ),
                ),
                ("created_date", models.DateField(blank=True, null=True)),
                ("closed_date", models.DateField(blank=True, null=True)),
                ("url", models.URLField(blank=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to="teams.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-closed_date", "-created_date"],
            },
        ),
    ]
