# Generated by Django 5.2.17 on 2026-08-28 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0013_azuredevopssettings_support_auto_sync_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="related_work_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: the change/user story this ticket led to, if any. Set manually — not auto-matched.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_tickets",
                to="teams.workitem",
            ),
        ),
    ]
