# Generated by Django 5.2.17 on 2026-08-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0014_supportticket_related_work_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="career_start_date",
            field=models.DateField(
                blank=True,
                help_text="When this person's professional career began — used to compute total years of experience.",
                null=True,
                verbose_name="Career start date",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[("permanent", "Permanent"), ("contract", "Contract")],
                help_text="Whether this person is a permanent employee or on contract.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_photos/"
            ),
        ),
    ]
