# Generated by Django 5.2.17 on 2026-08-28 03:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "global_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("2-critical", "2-Critical"),
                            ("3-high", "3-High"),
                            ("4-medium", "4-Medium"),
                        ],
                        default="3-high",
                        max_length=20,
                    ),
                ),
                (
                    "architecture_container",
                    models.CharField(blank=True, max_length=150),
                ),
                ("gsc_owner", models.CharField(blank=True, max_length=150)),
                ("it_perimeter_lvl2", models.CharField(blank=True, max_length=150)),
                ("it_perimeter_lvl3", models.CharField(blank=True, max_length=150)),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("application", "Application"),
                            ("service", "Service"),
                        ],
                        default="application",
                        max_length=20,
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("business_capabilities", "Business Capabilities"),
                            ("it_capabilities", "IT Capabilities"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "procurement_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in_house", "In House Development"),
                            ("software_package", "Software Package"),
                        ],
                        max_length=30,
                    ),
                ),
                ("officer", models.CharField(blank=True, max_length=150)),
                ("country", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TransitionSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects_led",
                        to="teams.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[("planned", "Planned"), ("adhoc", "Ad Hoc")],
                        default="planned",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("sdm_attention", models.BooleanField(default=False)),
                ("remarks", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="projects.area",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_assigned",
                        to="teams.employee",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_received",
                        to="teams.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransitionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=150)),
                ("document", models.CharField(max_length=200)),
                ("purpose", models.TextField(blank=True)),
                ("owner", models.CharField(blank=True, max_length=150)),
                ("comments", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "systems",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documents",
                        to="projects.transitionsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
