# Generated by Django 5.2.17 on 2026-08-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="backup_coverage_level",
            field=models.CharField(
                blank=True,
                help_text="e.g. Total, Partial, No backup.",
                max_length=200,
                verbose_name="Backup coverage level",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="backup_limitations",
            field=models.TextField(
                blank=True,
                verbose_name="Known limitations or risks regarding backup/recoverability",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="backup_solution",
            field=models.CharField(
                blank=True,
                help_text="e.g. Veeam, TSM, Commvault, BRMS.",
                max_length=300,
                verbose_name="Backup solution used",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="backup_status",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="application",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="globalgov_lvl1",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="GlobalGov lvl.1"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="globalgov_lvl2",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="GlobalGov lvl.2"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="last_backup_date",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Date of last backup"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="last_rebuild_date",
            field=models.CharField(
                blank=True,
                help_text="Free text, since sources record this as either a date or a note (e.g. 'Never').",
                max_length=100,
                verbose_name="Last date app rebuilt using the backup",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="last_restore_date",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Date of last data restore"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="p_level",
            field=models.CharField(blank=True, max_length=20, verbose_name="P Level"),
        ),
        migrations.AddField(
            model_name="application",
            name="rebuild_confidence",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=10,
                verbose_name="Confidence to rebuild if erased in production",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
