# Generated by Django 5.2.17 on 2026-08-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_application_backup_coverage_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="domain",
            field=models.CharField(
                blank=True,
                help_text="Business/functional domain, e.g. Tax Filing, Payments, Identity & KYC.",
                max_length=150,
            ),
        ),
    ]
