# Generated by Django 5.2.17 on 2026-08-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_application_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitiondocument",
            name="available",
            field=models.BooleanField(
                default=False,
                help_text="Whether this document has actually been gathered and uploaded yet.",
                verbose_name="Document collected / digitized",
            ),
        ),
    ]
