# Generated by Django 5.2.17 on 2026-08-29 02:57

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("projects", "0004_transitiondocument_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.application",
            ),
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("introduction", "Introduction"),
                            ("governance", "Governance & Transition Management"),
                            ("app_technical", "Application & Technical Documentation"),
                            ("integration", "Integration & Interdependency Landscape"),
                            ("operations", "Operations & Support"),
                            ("knowledge_transfer", "Knowledge Transfer"),
                            ("compliance", "Compliance & Administrative"),
                            ("audit", "Audit & Compliance Checklist"),
                            ("deployment", "Deployment"),
                            ("risk", "Risk"),
                        ],
                        max_length=30,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "file",
                    models.FileField(upload_to=projects.models.document_version_path),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
    ]
