# Generated by Django 5.2.17 on 2026-08-29 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_application_documentversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitiondocument",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: scope this checklist item to one project. Left blank, it's a shared/generic item shown for every project.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transition_documents",
                to="projects.project",
            ),
        ),
    ]
