# Generated by Django 5.2.17 on 2026-08-29 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_transitiondocument_project"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transitiondocument",
            options={"ordering": ["project__name", "order", "id"]},
        ),
        migrations.AlterField(
            model_name="transitiondocument",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="The project (application) this transition checklist item belongs to. Each project has its own independent checklist — nothing here is shared across projects.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transition_documents",
                to="projects.project",
            ),
        ),
    ]
