# Generated by Django 5.2.17 on 2026-08-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_transitiondocument_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="original_filename",
            field=models.CharField(
                blank=True,
                help_text="The file name as the uploader had it, kept for reference — the stored file itself is renamed to a consistent versioned name.",
                max_length=255,
            ),
        ),
    ]
