# Generated by Django 5.2.17 on 2026-08-29 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_documentversion_original_filename"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transitiondocument",
            options={"ordering": ["project__name", "template__order", "id"]},
        ),
        migrations.RemoveField(
            model_name="transitiondocument",
            name="category",
        ),
        migrations.RemoveField(
            model_name="transitiondocument",
            name="document",
        ),
        migrations.RemoveField(
            model_name="transitiondocument",
            name="order",
        ),
        migrations.RemoveField(
            model_name="transitiondocument",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="transitiondocument",
            name="purpose",
        ),
        migrations.RemoveField(
            model_name="transitiondocument",
            name="systems",
        ),
        migrations.CreateModel(
            name="TransitionDocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=150)),
                ("document", models.CharField(max_length=200)),
                ("purpose", models.TextField(blank=True)),
                ("owner", models.CharField(blank=True, max_length=150)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "archived",
                    models.BooleanField(
                        default=False,
                        help_text="Archived templates no longer appear on any project's active checklist, but any files already uploaded against them are kept rather than deleted.",
                    ),
                ),
                (
                    "systems",
                    models.ManyToManyField(
                        blank=True,
                        related_name="template_documents",
                        to="projects.transitionsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="transitiondocument",
            name="template",
            field=models.ForeignKey(
                help_text="The shared checklist-item definition this row is a per-project instance of.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="projects.transitiondocumenttemplate",
            ),
        ),
    ]
